"use client";
import type { ColumnDef } from "@tanstack/react-table";
import { ArrowUpDown, MoreHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import type { RegistrationListItem } from "@/lib/organizer/registrations/registration-types";
import { formatRegistrationDate } from "@/lib/organizer/registrations/registration-formatters";
import { RegistrationStatusBadge } from "./registration-status-badge"; import { EligibilityBadge } from "./eligibility-badge"; import { TeamStatusBadge } from "./team-status-badge";

export function getRegistrationColumns(actions: { view: (row: RegistrationListItem) => void; approve: (row: RegistrationListItem) => void; reject: (row: RegistrationListItem) => void; waitlist: (row: RegistrationListItem) => void }): ColumnDef<RegistrationListItem>[] {
  return [
    { id: "select", header: ({ table }) => <input aria-label="Select all registrations on this page" type="checkbox" checked={table.getIsAllPageRowsSelected()} onChange={table.getToggleAllPageRowsSelectedHandler()} className="size-4 accent-orange-500" />, cell: ({ row }) => <input aria-label={`Select ${row.original.student.fullName}`} type="checkbox" checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()} className="size-4 accent-orange-500" />, enableSorting: false, enableHiding: false },
    { accessorKey: "student", header: "Student", cell: ({ row }) => <div className="flex min-w-56 items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-orange-500/10 text-xs font-semibold text-orange-400">{row.original.student.fullName.split(" ").map((word) => word[0]).slice(0, 2).join("")}</span><div><p className="font-medium">{row.original.student.fullName}</p><p className="text-xs text-muted-foreground">{row.original.student.email}</p><p className="text-[10px] text-muted-foreground">{row.original.student.studentId}</p></div></div> },
    { accessorKey: "event", header: "Event", cell: ({ row }) => <div className="min-w-52"><p className="font-medium">{row.original.event.name}</p><p className="text-xs text-muted-foreground">{row.original.event.track} · {row.original.event.season} {row.original.event.year}</p></div> },
    { accessorKey: "registeredAt", header: ({ column }) => <Button variant="ghost" size="sm" onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}>Registered At <ArrowUpDown /></Button>, cell: ({ row }) => <div className="min-w-36"><p>{formatRegistrationDate(row.original.registeredAt)}</p><p className="text-xs text-muted-foreground">{row.original.registeredRelative}</p></div> },
    { accessorKey: "eligibility", header: "Eligibility", cell: ({ row }) => <EligibilityBadge status={row.original.eligibility} reason={row.original.eligibilityReason} /> },
    { accessorKey: "teamStatus", header: "Team Status", cell: ({ row }) => <div><TeamStatusBadge status={row.original.teamStatus} />{row.original.team && <p className="mt-1 text-[10px] text-muted-foreground">{row.original.team.name} · {row.original.team.role}</p>}</div> },
    { accessorKey: "status", header: "Registration Status", cell: ({ row }) => <RegistrationStatusBadge status={row.original.status} /> },
    { accessorKey: "reviewedBy", header: "Reviewed By", cell: ({ row }) => row.original.reviewedBy ? <div><p>{row.original.reviewedBy}</p><p className="text-xs text-muted-foreground">{row.original.reviewedAt}</p></div> : <span className="text-xs text-muted-foreground">Not reviewed yet</span> },
    { id: "actions", header: "Actions", enableHiding: false, cell: ({ row }) => <div className="flex items-center justify-end gap-1"><Button variant="outline" size="sm" onClick={() => actions.view(row.original)}>View Details</Button>{row.original.status === "Pending" && <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Actions for ${row.original.student.fullName}`}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => actions.approve(row.original)}>Approve</DropdownMenuItem><DropdownMenuItem onClick={() => actions.reject(row.original)} className="text-red-400">Reject</DropdownMenuItem><DropdownMenuItem onClick={() => actions.waitlist(row.original)}>Move to Waitlist</DropdownMenuItem><DropdownMenuItem onClick={() => void navigator.clipboard.writeText(row.original.id)}>Copy Registration ID</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</div> },
  ];
}
