"use client";
/* eslint-disable react-hooks/incompatible-library */
import { useForm } from "react-hook-form"; import { zodResolver } from "@hookform/resolvers/zod";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { RegistrationNotificationInput } from "@/lib/organizer/registrations/registration-types"; import { notificationSchema } from "@/lib/organizer/registrations/registration-validation";
export function SendRegistrationNotificationDialog({ open, onOpenChange, selectedCount, filteredCount, onConfirm }: { open: boolean; onOpenChange: (open: boolean) => void; selectedCount: number; filteredCount: number; onConfirm: (input: RegistrationNotificationInput) => void }) {
  const form = useForm<RegistrationNotificationInput>({ resolver: zodResolver(notificationSchema), defaultValues: { audience: selectedCount ? "Selected registrations" : "All filtered registrations", channels: ["In-app"], subject: "", message: "", schedule: "now" } });
  const audience = form.watch("audience"); const recipientCount = audience === "Selected registrations" ? selectedCount : filteredCount;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Send notification</DialogTitle><DialogDescription>{recipientCount} recipients in the current audience.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={form.handleSubmit(onConfirm)}>
    <label className="block space-y-1.5 text-sm font-medium">Audience<Select value={audience} onValueChange={(value) => value && form.setValue("audience", value)}><SelectTrigger className="mt-1 w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Selected registrations">Selected registrations ({selectedCount})</SelectItem><SelectItem value="All filtered registrations">All filtered registrations ({filteredCount})</SelectItem><SelectItem value="Pending registrations">Pending registrations</SelectItem><SelectItem value="Approved participants">Approved participants</SelectItem><SelectItem value="Waitlisted registrations">Waitlisted registrations</SelectItem></SelectContent></Select></label>
    <div className="flex gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.watch("channels").includes("In-app")} onChange={(event) => form.setValue("channels", event.target.checked ? [...form.getValues("channels"), "In-app"] : form.getValues("channels").filter((value) => value !== "In-app"), { shouldValidate: true })} className="size-4 accent-orange-500" /> In-app</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.watch("channels").includes("Email")} onChange={(event) => form.setValue("channels", event.target.checked ? [...form.getValues("channels"), "Email"] : form.getValues("channels").filter((value) => value !== "Email"), { shouldValidate: true })} className="size-4 accent-orange-500" /> Email</label></div>
    <label className="block space-y-1.5 text-sm font-medium">Subject<Input {...form.register("subject")} className="mt-1" />{form.formState.errors.subject && <span className="text-xs text-red-400">{form.formState.errors.subject.message}</span>}</label>
    <label className="block space-y-1.5 text-sm font-medium">Message<Textarea {...form.register("message")} className="mt-1 min-h-28" />{form.formState.errors.message && <span className="text-xs text-red-400">{form.formState.errors.message.message}</span>}</label>
    <DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={recipientCount === 0}>Send now</Button></DialogFooter>
  </form></DialogContent></Dialog>;
}
