"use client";
/* eslint-disable react-hooks/incompatible-library */
import { useState } from "react"; import { useForm } from "react-hook-form"; import { zodResolver } from "@hookform/resolvers/zod"; import { useMutation, useQuery } from "@tanstack/react-query"; import { z } from "zod"; import { Bell, Copy, Mail, MoreHorizontal, Plus, Send } from "lucide-react"; import { enqueueSnackbar } from "notistack";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Textarea } from "@/components/ui/textarea"; import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"; import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"; import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { ManagementPageHeader } from "@/components/organizer/shared/management-page-header"; import { ManagementSkeleton } from "@/components/organizer/shared/management-states"; import { organizerManagementService } from "@/services/organizer-management.service";
import { getDashboardFilterOptions } from "@/services/admin-dashboard.service";
const composeSchema = z.object({ event: z.string().min(1), audience: z.string().min(1), subject: z.string().min(3), message: z.string().min(10), sendMode: z.enum(["now", "schedule"]), scheduledAt: z.string().optional() }).refine((data) => data.sendMode !== "schedule" || Boolean(data.scheduledAt), { path: ["scheduledAt"], message: "Select a future time" });
type ComposeValues = z.infer<typeof composeSchema>;
export function NotificationsClient() {
  const [tab, setTab] = useState("compose"); const scheduled = useQuery({ queryKey: ["organizer-notifications-scheduled"], queryFn: () => organizerManagementService.getScheduledNotifications() }); const sent = useQuery({ queryKey: ["organizer-notifications-sent"], queryFn: () => organizerManagementService.getSentNotifications() }); const templates = useQuery({ queryKey: ["organizer-notification-templates"], queryFn: () => organizerManagementService.getNotificationTemplates() }); const eventsQuery = useQuery({ queryKey: ["organizer-dashboard-filter-options"], queryFn: getDashboardFilterOptions });
  const form = useForm<ComposeValues>({ resolver: zodResolver(composeSchema), defaultValues: { event: "", audience: "", subject: "", message: "", sendMode: "now", scheduledAt: "" } }); const values = form.watch(); const canSend = Boolean(values.event && values.audience);
  const sendMutation = useMutation({ mutationFn: (data: ComposeValues) => organizerManagementService.sendReminder({ eventId: data.event, audience: data.audience, subject: data.subject, message: data.message, scheduledAt: data.sendMode === "schedule" ? data.scheduledAt : undefined, channels: ["in_app", "email"] }), onSuccess: () => { enqueueSnackbar(values.sendMode === "now" ? "Reminder sent successfully" : "Reminder scheduled successfully", { variant: "success" }); form.reset(); }, onError: () => enqueueSnackbar("Unable to send reminder", { variant: "error" }) });
  const submit = (data: ComposeValues) => sendMutation.mutate(data);
  return <div className="space-y-6"><ManagementPageHeader eyebrow="Event communication" title="Notifications" description="Compose, schedule and monitor communications for your assigned events." actions={<Button onClick={() => setTab("compose")}><Plus /> New Notification</Button>} />
    <Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="compose">Compose</TabsTrigger><TabsTrigger value="scheduled">Scheduled</TabsTrigger><TabsTrigger value="sent">Sent</TabsTrigger><TabsTrigger value="templates">Templates</TabsTrigger></TabsList>
      <TabsContent value="compose" className="mt-6"><div className="grid gap-6 xl:grid-cols-3"><form onSubmit={form.handleSubmit(submit)} className="space-y-4 rounded-2xl border border-border bg-card/60 p-5 xl:col-span-2"><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1.5 text-sm font-medium">Event<Select value={values.event} onValueChange={(value) => value && form.setValue("event", value)}><SelectTrigger className="mt-1 w-full"><SelectValue placeholder="Select event" /></SelectTrigger><SelectContent>{eventsQuery.data?.events.map((event) => <SelectItem key={event.value} value={event.value}>{event.label}</SelectItem>)}</SelectContent></Select></label><label className="space-y-1.5 text-sm font-medium">Audience<Select value={values.audience} onValueChange={(value) => value && form.setValue("audience", value)}><SelectTrigger className="mt-1 w-full"><SelectValue placeholder="Select audience" /></SelectTrigger><SelectContent>{["All Participants", "Pending Registrations", "Approved Participants", "Waitlisted Students", "Team Leaders", "Teams Not Submitted", "Mentors", "Judges"].map((audience) => <SelectItem key={audience} value={audience}>{audience}</SelectItem>)}</SelectContent></Select></label></div><div className="flex gap-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked className="accent-orange-500" /> In-app</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked className="accent-orange-500" /> Email</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-orange-500" /> Push</label></div><label className="block space-y-1.5 text-sm font-medium">Subject<Input {...form.register("subject")} className="mt-1" />{form.formState.errors.subject && <span className="text-xs text-red-400">{form.formState.errors.subject.message}</span>}</label><label className="block space-y-1.5 text-sm font-medium">Message<Textarea {...form.register("message")} className="mt-1 min-h-40" />{form.formState.errors.message && <span className="text-xs text-red-400">{form.formState.errors.message.message}</span>}</label><div className="grid gap-4 sm:grid-cols-2"><Select value={values.sendMode} onValueChange={(value) => value && form.setValue("sendMode", value as ComposeValues["sendMode"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="now">Send Now</SelectItem><SelectItem value="schedule">Schedule</SelectItem></SelectContent></Select>{values.sendMode === "schedule" && <Input type="datetime-local" {...form.register("scheduledAt")} />}</div><div className="flex items-center justify-between rounded-xl bg-muted/40 p-3"><span className="text-sm">Recipients are resolved by the API</span><Button type="submit" disabled={!canSend || sendMutation.isPending}><Send /> {sendMutation.isPending ? "Sending..." : values.sendMode === "now" ? "Send Reminder" : "Schedule"}</Button></div></form>
        <div className="rounded-2xl border border-border bg-card/60 p-5"><h2 className="font-semibold">Preview</h2><div className="mt-5 rounded-xl border border-border bg-background p-4"><div className="flex items-center gap-2 text-orange-400"><Bell className="size-4" /><span className="text-xs font-semibold">SEAL · now</span></div><h3 className="mt-3 font-semibold">{values.subject || "Notification subject"}</h3><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{values.message || "Your message preview will appear here."}</p></div><div className="mt-4 rounded-xl border border-border p-4"><Mail className="size-4 text-muted-foreground" /><p className="mt-2 text-xs text-muted-foreground">Email preview · {values.event || "No event selected"}</p></div></div></div></TabsContent>
      <TabsContent value="scheduled" className="mt-6">{scheduled.isLoading ? <ManagementSkeleton /> : <div className="overflow-hidden rounded-2xl border border-border"><Table><TableHeader><TableRow><TableHead>Notification</TableHead><TableHead>Event</TableHead><TableHead>Audience</TableHead><TableHead>Scheduled</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{scheduled.data?.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.subject}</TableCell><TableCell>{item.event}</TableCell><TableCell>{item.audience}</TableCell><TableCell>{item.scheduledAt}</TableCell><TableCell><Badge variant="warning">{item.status}</Badge></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm"><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>Edit</DropdownMenuItem><DropdownMenuItem>Reschedule</DropdownMenuItem><DropdownMenuItem>Duplicate</DropdownMenuItem><DropdownMenuItem className="text-red-400">Cancel</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div>}</TabsContent>
      <TabsContent value="sent" className="mt-6">{sent.isLoading ? <ManagementSkeleton /> : <div className="overflow-hidden rounded-2xl border border-border"><Table><TableHeader><TableRow><TableHead>Notification</TableHead><TableHead>Event</TableHead><TableHead>Sent At</TableHead><TableHead>Recipients</TableHead><TableHead>Success / Failed</TableHead><TableHead>Read</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{sent.data?.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.subject}</TableCell><TableCell>{item.event}</TableCell><TableCell>{item.sentAt}</TableCell><TableCell>{item.recipients}</TableCell><TableCell><span className="text-emerald-400">{item.success}</span> / <span className="text-red-400">{item.failed}</span></TableCell><TableCell>{item.read}</TableCell><TableCell><Button variant="ghost" size="icon-sm"><Copy /></Button></TableCell></TableRow>)}</TableBody></Table></div>}</TabsContent>
      <TabsContent value="templates" className="mt-6">{templates.isLoading ? <ManagementSkeleton /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{templates.data?.map((template) => <div key={template.id} className="rounded-2xl border border-border bg-card/60 p-4"><h3 className="font-semibold">{template.name}</h3><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{template.message}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => { form.setValue("subject", template.subject); form.setValue("message", template.message); setTab("compose"); }}>Use Template</Button><Button size="sm" variant="outline">Edit</Button><Button size="icon-sm" variant="ghost"><Copy /></Button></div></div>)}</div>}</TabsContent>
    </Tabs></div>;
}
