"use client";
/* eslint-disable react-hooks/incompatible-library */
import { useMemo, useState } from "react"; import { useQuery } from "@tanstack/react-query"; import { flexRender, getCoreRowModel, useReactTable, type ColumnDef } from "@tanstack/react-table";
import { AreaChart } from "@tremor/react"; import { CheckCircle2, Clock3, FileCheck2, FileWarning, MoreHorizontal, Search, Send, Users } from "lucide-react"; import { enqueueSnackbar } from "notistack";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Badge } from "@/components/ui/badge"; import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"; import { Sheet, SheetContent, SheetDescription, SheetTitle } from "@/components/ui/sheet"; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ManagementPageHeader } from "@/components/organizer/shared/management-page-header"; import { ManagementMetricGrid } from "@/components/organizer/shared/management-metric-grid"; import { ManagementEmpty, ManagementError, ManagementSkeleton } from "@/components/organizer/shared/management-states";
import type { OrganizerSubmission, SubmissionFilters } from "@/lib/organizer/management-types"; import { organizerManagementService } from "@/services/organizer-management.service";
const statusVariant = { "On Time": "success", Late: "warning", Invalid: "destructive", Reopened: "ai" } as const; const evaluationVariant = { "Not Assigned": "outline", Pending: "warning", "In Progress": "ai", Evaluated: "success" } as const;
export function SubmissionsClient() {
  const [filters, setFilters] = useState<SubmissionFilters>({ search: "", status: "All", evaluation: "All", page: 1, limit: 10 }); const [selected, setSelected] = useState<OrganizerSubmission | null>(null); const [drawerOpen, setDrawerOpen] = useState(false); const [dialog, setDialog] = useState<"assign" | "reopen" | null>(null);
  const query = useQuery({ queryKey: ["organizer-submissions", filters], queryFn: () => organizerManagementService.getSubmissions(filters) }); const activityQuery = useQuery({ queryKey: ["organizer-submission-activity"], queryFn: () => organizerManagementService.getSubmissionActivity() });
  const summaryQuery = useQuery({ queryKey: ["organizer-submission-summary"], queryFn: () => organizerManagementService.getSubmissionSummary() });
  const columns = useMemo<ColumnDef<OrganizerSubmission>[]>(() => [
    { accessorKey: "team", header: "Team", cell: ({ row }) => <div><p className="font-medium">{row.original.team}</p><p className="text-xs text-muted-foreground">{row.original.project}</p></div> }, { accessorKey: "event", header: "Event" }, { accessorKey: "round", header: "Round" }, { accessorKey: "track", header: "Track" }, { accessorKey: "submittedAt", header: "Submitted At" },
    { accessorKey: "status", header: "Submission Status", cell: ({ row }) => <Badge variant={statusVariant[row.original.status]}>{row.original.status}</Badge> }, { accessorKey: "evaluationStatus", header: "Evaluation", cell: ({ row }) => <Badge variant={evaluationVariant[row.original.evaluationStatus]}>{row.original.evaluationStatus}</Badge> },
    { id: "actions", header: "Actions", cell: ({ row }) => <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm" aria-label={`Actions for ${row.original.project}`}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => { setSelected(row.original); setDrawerOpen(true); }}>View Submission</DropdownMenuItem><DropdownMenuItem onClick={() => window.open(row.original.repository, "_blank")}>Open Repository</DropdownMenuItem><DropdownMenuItem onClick={() => { setSelected(row.original); setDialog("assign"); }}>Assign Judge</DropdownMenuItem><DropdownMenuItem onClick={() => enqueueSnackbar("Submission marked valid", { variant: "success" })}>Mark Valid</DropdownMenuItem><DropdownMenuItem className="text-red-400">Mark Invalid</DropdownMenuItem><DropdownMenuItem onClick={() => { setSelected(row.original); setDialog("reopen"); }}>Reopen Submission</DropdownMenuItem></DropdownMenuContent></DropdownMenu> },
  ], []); const table = useReactTable({ data: query.data?.data ?? [], columns, getCoreRowModel: getCoreRowModel() });
  const summary = summaryQuery.data; const metrics = [{ label: "Total Submissions", value: summary?.total ?? 0, detail: "Across all assigned events", icon: FileCheck2 }, { label: "Submitted On Time", value: summary?.onTime ?? 0, detail: "Before round deadline", icon: CheckCircle2 }, { label: "Late Submissions", value: summary?.late ?? 0, detail: "Require review", icon: Clock3 }, { label: "Pending Evaluation", value: summary?.pending ?? 0, detail: "Waiting for judges", icon: FileWarning }, { label: "Evaluated", value: summary?.evaluated ?? 0, detail: "Completed evaluations", icon: CheckCircle2 }, { label: "Teams Not Submitted", value: summary?.notSubmitted ?? 0, detail: "From dashboard submission summary", icon: Users }];
  return <div className="space-y-6"><ManagementPageHeader eyebrow="Delivery operations" title="Submissions" description="Monitor team deliverables and evaluation progress across assigned events." actions={<Button variant="outline"><Send /> Send Reminder</Button>} /><ManagementMetricGrid metrics={metrics} />
    <div className="rounded-2xl border border-border bg-card/60 p-5"><h2 className="font-semibold">Submission Activity</h2><p className="mt-1 text-sm text-muted-foreground">Live activity returned by the dashboard submissions API.</p>{activityQuery.data ? <AreaChart data={activityQuery.data} index="date" categories={["Submissions"]} colors={["orange"]} className="mt-5 h-64" showAnimation={false} /> : <div className="mt-5 h-64 animate-pulse rounded-xl bg-muted/50" />}</div>
    <div className="flex flex-col gap-3 rounded-2xl border border-border bg-card/60 p-4 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value, page: 1 })} placeholder="Search team or project..." className="pl-9" /></div>{[["status", ["All", "On Time", "Late", "Invalid", "Reopened"]], ["evaluation", ["All", "Not Assigned", "Pending", "In Progress", "Evaluated"]]].map(([field, options]) => <Select key={String(field)} value={filters[field as "status" | "evaluation"]} onValueChange={(value) => value && setFilters({ ...filters, [String(field)]: value, page: 1 })}><SelectTrigger className="w-full md:w-48"><SelectValue /></SelectTrigger><SelectContent>{(options as string[]).map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select>)}</div>
    {query.isError ? <ManagementError onRetry={() => void query.refetch()} /> : query.isLoading ? <ManagementSkeleton /> : !query.data?.data.length ? <ManagementEmpty label="submissions" /> : <div className="overflow-hidden rounded-2xl border border-border"><Table><TableHeader>{table.getHeaderGroups().map((group) => <TableRow key={group.id}>{group.headers.map((header) => <TableHead key={header.id}>{flexRender(header.column.columnDef.header, header.getContext())}</TableHead>)}</TableRow>)}</TableHeader><TableBody>{table.getRowModel().rows.map((row) => <TableRow key={row.id}>{row.getVisibleCells().map((cell) => <TableCell key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</TableCell>)}</TableRow>)}</TableBody></Table><div className="flex items-center justify-between border-t p-3 text-sm"><span>{query.data.pagination.total} submissions</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={filters.page === 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>Previous</Button><Button variant="outline" size="sm" disabled={filters.page >= query.data.pagination.totalPages} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Next</Button></div></div></div>}
    <Sheet open={drawerOpen} onOpenChange={setDrawerOpen}><SheetContent side="right" className="w-full overflow-y-auto p-5 sm:max-w-2xl"><SheetTitle>{selected?.project}</SheetTitle><SheetDescription>{selected?.team} · {selected?.id}</SheetDescription>{selected && <Tabs defaultValue="overview" className="mt-6"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="files">Files & Links</TabsTrigger><TabsTrigger value="versions">Versions</TabsTrigger><TabsTrigger value="evaluation">Evaluation</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList><TabsContent value="overview" className="mt-5 space-y-3"><p>{selected.description}</p><p>{selected.event} · {selected.round} · {selected.track}</p><p>Submitted {selected.submittedAt}</p></TabsContent><TabsContent value="files" className="mt-5 space-y-3"><a className="block text-orange-400 underline" href={selected.repository} target="_blank">Repository</a><a className="block text-orange-400 underline" href={selected.demo} target="_blank">Demo</a></TabsContent><TabsContent value="versions" className="mt-5 rounded-xl border p-4">v3 · Submitted by team leader · Final update</TabsContent><TabsContent value="evaluation" className="mt-5 rounded-xl border p-4">{selected.evaluationStatus}{selected.score ? ` · Score ${selected.score}` : ""}</TabsContent><TabsContent value="history" className="mt-5 rounded-xl border p-4">Submitted → Updated → Evaluation pending</TabsContent></Tabs>}</SheetContent></Sheet>
    <Dialog open={dialog !== null} onOpenChange={(open) => !open && setDialog(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>{dialog === "assign" ? "Assign Judge" : "Reopen Submission"}</DialogTitle><DialogDescription>{selected?.project}</DialogDescription></DialogHeader>{dialog === "assign" ? <div className="space-y-3"><Input placeholder="Judge" /><Input placeholder="Round / track" /><Input placeholder="Assignment note" /></div> : <div className="space-y-3"><Textarea placeholder="Reason for reopening" /><Input type="datetime-local" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked className="accent-orange-500" /> Send notification</label></div>}<DialogFooter><Button variant="outline" onClick={() => setDialog(null)}>Cancel</Button><Button onClick={() => { enqueueSnackbar(dialog === "assign" ? "Judge assigned" : "Submission reopened", { variant: "success" }); setDialog(null); }}>Confirm</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
